### ISSUE TITLE
请教信

### ISSUE THREAD

**Issue by surviveMiao** [sunlicai/HiCMAE#1]
您好，我想要了解一下有关提取mel谱图的代码，在progress文件夹下似乎没有

**Comment by sunlicai** [comment]
Thanks for your interest in our work!

The code for audio spectorgram can be found in the dataloader.

https://github.com/sunlicai/HiCMAE/blob/1e42a46acbd979ff47d86fb2aef69fd86045cee8/kinetics_av.py#L622-L625

**Comment by surviveMiao** [comment]
> Thanks for your interest in our work!
> 
> The code for audio spectorgram can be found in the dataloader.
> 
> https://github.com/sunlicai/HiCMAE/blob/1e42a46acbd979ff47d86fb2aef69fd86045cee8/kinetics_av.py#L622-L625
ok！Thanks
