### ISSUE TITLE
About pretraining code

### ISSUE THREAD

**Issue by chae0382** [sunlicai/HiCMAE#2]
I am interested in your research. Do you have pretraining code available, or do you have plan to release the pretraining code?

**Comment by youcaiSUN** [comment]
Hi @chae0382, thanks for your interst in our work! We will release the pre-training code in next week. Stay tuned!

**Comment by chae0382** [comment]
Thank you for sharing the great work!

**Comment by sunlicai** [comment]
Hi @chae0382 , we've uploaded the pre-training code, have a try!

**Comment by chae0382** [comment]
Hi @sunlicai, thank you!
