### ISSUE TITLE
Error: pip install -r requirements.txt

### ISSUE THREAD

**Issue by YTYun** [sunlicai/HiCMAE#3]
I have some problems when I run the project. I don't know how to deal with it as follows:
And it happened when I pip install -r requirements.txt.
![error](https://github.com/sunlicai/HiCMAE/assets/127875432/781c8a15-6fff-437b-80b3-3dbed7f867c4)

**Comment by sunlicai** [comment]
Hi @YTYun，it is not necessary to install all packages in requirement.txt. You just install the main ones shown in README.md.
