### ISSUE TITLE
Error：未定义pretrained_config参数

### ISSUE THREAD

**Issue by Shawnie-qi** [sunlicai/HiCMAE#4]
请问我这边在定义model的时候报错未定义pretrained_config参数的错误该怎么解决呢？报错文件在modeling_finetune_av.py
<img width="682" alt="858a54930d94bb0b18aae609fd58059" src="https://github.com/sunlicai/HiCMAE/assets/80382313/3f12b6fa-5d6e-47c7-8493-0c51f263252c">

**Comment by sunlicai** [comment]
Is your timm version == 0.4.12?

**Comment by Shawnie-qi** [comment]
my timm version==0.9.16, now I solve this problem, thanx!
