### ISSUE TITLE
The split files of MSP-IMPROV and Werewolf-XL datasets

### ISSUE THREAD

**Issue by Sanzhen3** [sunlicai/HiCMAE#9]
Dear authors,
Thank you for your great contributions!

As described above, could you provide me with the split files of MSP-IMPROV and Werewolf-XL datasets?

I couldn't find them in the official databases, and in order to replicate the results from the paper, I am reaching out to you for assistance.

Any reply will be appreciated!

Thanks a lot.

**Comment by sunlicai** [comment]
Hi @Sanzhen3, the split files of MSP-IMPROV and Werewolf-XL datasets have been uploaded. You can check them in the directory of ./saved/data.

**Comment by Sanzhen3** [comment]
@sunlicai , thank you for your nice reply!
I will have a quick try.

**Comment by Sanzhen3** [comment]
Dear @sunlicai, 
Apologize for bothering you again.

For the MSP-IMPROV and AVCAffe datasets, I have sent the application letters to their offical e-mail accounts. But unfortunately, over the past week, all of my e-mails have gone unanswered. Therefore, I am reaching out once again to kindly request your assistance due to the urgent project deadline.

If it's convenient, could you please share the downloaded datasets via Baidu Netdisk or aliyunpan? 
My email address is sanzhen033@gmail.com.

Looking forward to hearing from you.
Thank you once again for your kind assistance.

**Comment by sunlicai** [comment]
Hi @Sanzhen3！

Due to the copyright issue, I could not share the MSP-IMPROV and AVCAffe datasets with you. You can re-send the application letter to the official or their their personal e-mail for more help.

Best，
Licai

**Comment by Sanzhen3** [comment]
Got it, Thank you for your reply.

**Comment by Sanzhen3** [comment]
Hi @sunlicai , Could you kindly provide us with the split files of RAVDESS dataset?

I have tried to adopt the split files you provided for RAVDESS dataset in MAE-DFER, but the results I obtained differ significantly from those reported in the HiCMAE paper, _i.e._, by ~9.0 UAR and WAR.

Therefore, I suspect that there might be issues with the split files I am using.

Looking forward to your response, and thank you for your kind help again!

**Comment by Sanzhen3** [comment]
> Hi @sunlicai , Could you kindly provide us with the split files of RAVDESS dataset?
> 
> I have tried to adopt the split files you provided for RAVDESS dataset in MAE-DFER, but the results I obtained differ significantly from those reported in the HiCMAE paper, _i.e._, by ~9.0 UAR and WAR.
> 
> Therefore, I suspect that there might be issues with the split files I am using.
> 
> Looking forward to your response, and thank you for your kind help again!

Dear @sunlicai, could you kindly provide me with some suggestions?
Thank you once again for your help.

**Comment by sunlicai** [comment]
Hi @Sanzhen3, sorry for late reply. I've uploaded he split files of RAVDESS.

**Comment by Sanzhen3** [comment]
> Hi @Sanzhen3, sorry for late reply. I've uploaded he split files of RAVDESS.

Got it, I will have a quick try. 😊

**Comment by Sanzhen3** [comment]
Hi @sunlicai, I found that the video and audio names of one sample in the split files of RAVDESS dataset are not consistent, which are shown as below.
![image](https://github.com/user-attachments/assets/09051652-fa93-4506-84f5-51d3c0715299)

Could you give me some advice?

Thank you for your help once again!

**Comment by sunlicai** [comment]
Actually, they are from the same sample but different files for different modalities. You can check the file naming convention for [RAVDESS](https://zenodo.org/records/1188976).

![image](https://github.com/user-attachments/assets/402debfe-2e07-4eab-bbe4-138bbcf34298)

**Comment by Sanzhen3** [comment]
Got it, I will check this again.
Thank you very much!
